name: "Frost Lab"
description: "The New Homepage for the Frost Lab at UCSF"
baseurl: ""
gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->
exclude: [vendor]
permalink: pretty
highlighter: pygments
markdown: kramdown
kramdown: 
  parse_block_html: true
